name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "task4-solntsev"
          heroku_email: "vitaly.solntsev@yandex.ru"
          healthcheck: "https://test4-solntsev.herokuapp.com/health/example.txt"
          checkstring: "ok"
      - run: npm test